def populateDataFileTemplate(valueDict):
    input_dim = valueDict['input_dim']
    hidden_dim = valueDict['hidden_dim']
    output_dim = valueDict['output_dim']
    w1 = valueDict['W1']
    b1 = valueDict['B1']
    w2 = valueDict['W2']
    b2 = valueDict['B2']
    
    template = '''/*
 * This is an autogenerated file. Modifications
 * might not be persistent.
 */
 #pragma once

    /** Input dimension for the model */
    #define INPUT_DIM %s
    /** Hidden dimension */
    #define HIDDEN_DIM %s
    /** Output dimension */
    #define OUTPUT_DIM %s
    ''' % (input_dim, hidden_dim, output_dim)

    template += '''
    /**
     * Input Weights (W1)
     * INPUT_DIM x HIDDEN_DIM 
     */
    static const float W1[INPUT_DIM * HIDDEN_DIM] = {%s};
    /**
     * Input Bias (B1)
     * HIDDEN_DIM 
     */
    static const float B1[HIDDEN_DIM] = {%s};
    ''' % (w1, b1)

    template += '''
    /**
     * Output Weights (W2)
     * HIDDEN_DIM X OUTPUT_DIM 
     */
    static const float W2[HIDDEN_DIM * OUTPUT_DIM] = {%s};
    /**
     * Output Bias (B2)
     * OUTPUT_DIM 
     */
    static const float B2[OUTPUT_DIM] = {%s};
    ''' % (w2, b2)

    template += '''


    '''
    return template